buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // KUNCI ARSITEKTUR: Menggunakan AGP 8.1.0 yang kompatibel dengan Java 17 di GitHub Actions
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
